// Code generated by cdpgen. DO NOT EDIT.

package headlessexperimental

import (
	"encoding/json"
	"log"
)

const (
	EventHeadlessExperimentalNeedsBeginFramesChanged = "HeadlessExperimental.needsBeginFramesChanged"
)

type Unmarshaler func() json.Unmarshaler

var EventConstants = map[string]Unmarshaler{
	EventHeadlessExperimentalNeedsBeginFramesChanged: func() json.Unmarshaler { return &NeedsBeginFramesChangedReply{} },
}

func GetEventReply(event string) (json.Unmarshaler, bool) {
	e, ok := EventConstants[event]
	if ok {
		return e(), ok
	}
	return nil, ok
}

// NeedsBeginFramesChangedReply is the reply for NeedsBeginFramesChanged events.
type NeedsBeginFramesChangedReply struct {
	NeedsBeginFrames bool `json:"needsBeginFrames"` // True if BeginFrames are needed, false otherwise.
}

// Unmarshal the byte array into a return value for NeedsBeginFramesChanged in the HeadlessExperimental domain.
func (a *NeedsBeginFramesChangedReply) UnmarshalJSON(b []byte) error {
	type Copy NeedsBeginFramesChangedReply
	c := &Copy{}
	err := json.Unmarshal(b, c)
	if err != nil {
		return err
	}
	*a = NeedsBeginFramesChangedReply(*c)
	return nil
}

// NeedsBeginFramesChangedReply returns whether or not the FrameID matches the reply value for NeedsBeginFramesChanged in the NeedsBeginFramesChanged domain.
func (a *NeedsBeginFramesChangedReply) MatchFrameID(frameID string, m []byte) bool {
	err := a.UnmarshalJSON(m)
	if err != nil {
		log.Fatalf("unmarshal error: NeedsBeginFramesChangedReply %s", err)
	}
	return true
}

// NeedsBeginFramesChangedReply returns the FrameID for NeedsBeginFramesChanged in the NeedsBeginFramesChanged domain.
func (a *NeedsBeginFramesChangedReply) GetFrameID() string {
	return ""
}
