// Code generated by cdpgen. DO NOT EDIT.

package inspector

import (
	"encoding/json"
)

const EventInspectorDetached = "Inspector.detached"

// DetachedReply is the reply for Detached events.
type DetachedReply struct {
	Reason string `json:"reason"` // The reason why connection has been terminated.
}

// Unmarshal the byte array into a return value for Detached in the Inspector domain.
func (a *DetachedReply) UnmarshalJSON(b []byte) error {
	type Copy DetachedReply
	c := &Copy{}
	err := json.Unmarshal(b, c)
	if err != nil {
		return err
	}
	*a = DetachedReply(*c)
	return nil
}

const EventInspectorTargetCrashed = "Inspector.targetCrashed"

// TargetCrashedReply is the reply for TargetCrashed events.
type TargetCrashedReply struct {
}

// Unmarshal the byte array into a return value for TargetCrashed in the Inspector domain.
func (a *TargetCrashedReply) UnmarshalJSON(b []byte) error {
	type Copy TargetCrashedReply
	c := &Copy{}
	err := json.Unmarshal(b, c)
	if err != nil {
		return err
	}
	*a = TargetCrashedReply(*c)
	return nil
}

const EventInspectorTargetReloadedAfterCrash = "Inspector.targetReloadedAfterCrash"

// TargetReloadedAfterCrashReply is the reply for TargetReloadedAfterCrash events.
type TargetReloadedAfterCrashReply struct {
}

// Unmarshal the byte array into a return value for TargetReloadedAfterCrash in the Inspector domain.
func (a *TargetReloadedAfterCrashReply) UnmarshalJSON(b []byte) error {
	type Copy TargetReloadedAfterCrashReply
	c := &Copy{}
	err := json.Unmarshal(b, c)
	if err != nil {
		return err
	}
	*a = TargetReloadedAfterCrashReply(*c)
	return nil
}
