// Code generated by cdpgen. DO NOT EDIT.

package profiler

import (
	"encoding/json"
	"log"

	"github.com/4ydx/cdp/protocol/debugger"
)

const (
	EventProfilerConsoleProfileFinished = "Profiler.consoleProfileFinished"
	EventProfilerConsoleProfileStarted  = "Profiler.consoleProfileStarted"
)

var EventConstants = map[string]json.Unmarshaler{
	EventProfilerConsoleProfileFinished: &ConsoleProfileFinishedReply{},
	EventProfilerConsoleProfileStarted:  &ConsoleProfileStartedReply{},
}

func GetEventReply(event string) (json.Unmarshaler, bool) {
	e, ok := EventConstants[event]
	return e, ok
}

// ConsoleProfileFinishedReply is the reply for ConsoleProfileFinished events.
type ConsoleProfileFinishedReply struct {
	ID       string            `json:"id"`              // No description.
	Location debugger.Location `json:"location"`        // Location of console.profileEnd().
	Profile  Profile           `json:"profile"`         // No description.
	Title    string            `json:"title,omitempty"` // Profile title passed as an argument to console.profile().
}

// Unmarshal the byte array into a return value for ConsoleProfileFinished in the Profiler domain.
func (a *ConsoleProfileFinishedReply) UnmarshalJSON(b []byte) error {
	type Copy ConsoleProfileFinishedReply
	c := &Copy{}
	err := json.Unmarshal(b, c)
	if err != nil {
		return err
	}
	*a = ConsoleProfileFinishedReply(*c)
	return nil
}

// ConsoleProfileFinishedReply returns whether or not the FrameID matches the reply value for ConsoleProfileFinished in the ConsoleProfileFinished domain.
func (a *ConsoleProfileFinishedReply) MatchFrameID(frameID string, m []byte) bool {
	err := a.UnmarshalJSON(m)
	if err != nil {
		log.Fatalf("unmarshal error: ConsoleProfileFinished", err)
	}
	return true
}

// ConsoleProfileFinishedReply returns the FrameID for ConsoleProfileFinished in the ConsoleProfileFinished domain.
func (a *ConsoleProfileFinishedReply) GetFrameID() string {
	return ""
}

// ConsoleProfileStartedReply is the reply for ConsoleProfileStarted events.
type ConsoleProfileStartedReply struct {
	ID       string            `json:"id"`              // No description.
	Location debugger.Location `json:"location"`        // Location of console.profile().
	Title    string            `json:"title,omitempty"` // Profile title passed as an argument to console.profile().
}

// Unmarshal the byte array into a return value for ConsoleProfileStarted in the Profiler domain.
func (a *ConsoleProfileStartedReply) UnmarshalJSON(b []byte) error {
	type Copy ConsoleProfileStartedReply
	c := &Copy{}
	err := json.Unmarshal(b, c)
	if err != nil {
		return err
	}
	*a = ConsoleProfileStartedReply(*c)
	return nil
}

// ConsoleProfileStartedReply returns whether or not the FrameID matches the reply value for ConsoleProfileStarted in the ConsoleProfileStarted domain.
func (a *ConsoleProfileStartedReply) MatchFrameID(frameID string, m []byte) bool {
	err := a.UnmarshalJSON(m)
	if err != nil {
		log.Fatalf("unmarshal error: ConsoleProfileStarted", err)
	}
	return true
}

// ConsoleProfileStartedReply returns the FrameID for ConsoleProfileStarted in the ConsoleProfileStarted domain.
func (a *ConsoleProfileStartedReply) GetFrameID() string {
	return ""
}
